config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get("/download_resume" => "application#download_resume")
  get("/contact_me" => "application#contact_me")

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def download_resume
    file = "#{Rails.root}/public/resume_jack_wong.pdf"
    if File.exists?(file)
      send_file file, :type=>"application/pdf", :x_sendfile=>true
    else
      flash[:notice] = 'File not found'
      redirect_to :index
    end
  end

  def contact_me
    ContactJackMailer.contact_jack_email(contact_me_params).deliver_now

    respond_to do |format|
      format.js do
        render "contact_jack_mailer/email_sent"
      end
    end
  end

  def contact_me_params
    params.require(:contact_me).permit(
      :name,
      :from_email,
      :message
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Jack Wong</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>
<%= yield %>

</body>
</html>

app/views/pages/_about.html.erb
<div class="about site-wrapper" id="about">

  <div class="site-wrapper-inner">

    <div class="container">

      <div class="inner cover mt-md-3">
        <h1 class="mb-md-5">
          About Jack
        </h1>
        <div class="img-container my-md-4">
          <img src="http://i.imgur.com/Vp0EwEll.jpg">
        </div>
        <div class="description mt-md-5">
          <p>
            Jack is a Gen-Y problem solver. He loves to deal with various kind of challenges, and see them get defeated.
          </p>
          <p>
            Jack believes that there are multiple solutions to a problem and there is no right nor wrong.
          </p>
          <p>
            Jack truly believes doing the right thing at the right time is the key to solving problems.
          </p>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/pages/_career_journey.html.erb
<div class="career-journey site-wrapper" id="career-journey">

  <div class="site-wrapper-inner">

    <div class="container">

      <div class="inner cover">
        <!DOCTYPE html>
        <html lang="en" class="no-js">
        	<head>
        		<meta charset="UTF-8" />
        		<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
        		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        	</head>
        	<body>
        		<div class="container">
        			<header class="clearfix">

        				<h1>Jack's Career Journey</h1>

        			</header>
        			<div class="main">
        				<ul class="cbp_tmtimeline">
        					<li>
        						<time class="cbp_tmtime" datetime="2017-01-10 18:30"><span></span> <span>2011</span></time>
        						<div class="cbp_tmicon cbp_tmicon-phone"><img src="http://i.imgur.com/52Bl7de.png" class="img-responsive" width="40px"></div>
        						<div class="cbp_tmlabel">
        							<h2>Purdue University @ West Lafayette</h2>
        							<p>Major in Computing & Information Systems</p>
                      <p>Minor in Management</p>
        						</div>
        					</li>
        					<li>
        						<time class="cbp_tmtime" datetime="2017-01-11T12:01"><span></span> <span>2014 July</span></time>
        						<div class="cbp_tmicon cbp_tmicon-screen"><img src="http://i.imgur.com/ZyMvSPG.png" class="img-responsive" width="40px"></div>
        						<div class="cbp_tmlabel">
        							<h2>Software Engineer @ Booster</h2>
                      <p>Ruby on Rails</p>
                      <p>TDD and BDD with Rspec, Capybara, Konacha and etc.</p>
                      <p>Agile via Scrum & Kanban</p>
        						</div>
        					</li>
        					<li>
        						<time class="cbp_tmtime" datetime="2017-01-17 05:36"><span></span> <span>2017 July</span></time>
        						<div class="cbp_tmicon cbp_tmicon-mail"><img src="http://i.imgur.com/bMfxXFd.png" class="img-responsive" width="40px"></div>
        						<div class="cbp_tmlabel">
        							<h2>Senior Software Engineer @ Fave Malaysia</h2>
        						</div>
        					</li>
        				</ul>
        			</div>
        		</div>
        	</body>
        </html>

      </div>
    </div>

  </div>

</div>

app/views/pages/_contact.html.erb
<div class="contact site-wrapper" id="contact">

  <div class="site-wrapper-inner">

    <div class="container">

      <div class="inner cover">
        <h1>
          Get In Touch
        </h1>

        <div class="mt-5">
          <%= form_for :contact_me, url: "/contact_me", method: :get, remote: true do |f| %>

          <div class="row">
            <div class="col-md-6 name-input-container">
              <%= f.text_field :name, placeholder: "NAME" %>
            </div>
            <div class="col-md-6">
              <%= f.email_field :from_email, placeholder: "EMAIL" %>
            </div>
          </div>

          <div class="row mt-4">
            <div class="col-md-12">
              <%= f.label :message %>
              <%= f.text_area :message %>
            </div>
          </div>

            <%= f.submit "Send Message", class: "mt-4" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/pages/_home.erb
<div class="home site-wrapper" id="home">

  <div class="site-wrapper-inner">

    <div class="container">

      <div class="masthead clearfix">
        <div class="container inner">
          <nav>
            <ul class="nav masthead-nav">
              <li class="active"><a class="navi" href="#home">Home</a></li>
              <li><a class="navi" href="#about">About</a></li>
              <li><a class="navi" href="#career-journey">Career Journey</a></li>
              <li><a class="navi" href="#contact">Contact</a></li>
              <li class="your-card-desktop hide-for-mobile">
                <a href="#your-card" data-toggle="modal" data-target="#myModal">Your Secret Card</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>

      <%= render "your_card" %>

      <div class="inner cover">
        <h1 class="cover-heading mb-md-5">Jack Wong</h1>
        <p class="lead">Being a curious person, I seek new technologies and strive to contribute my skills, experience and thoughts to
change the world, from worst to worse, good to better. "Everything goes back to the earth."</p>
        <p class="lead mt-md-4">
          <%= link_to "Download Resume", download_resume_path, class:"btn btn-lg btn-default", target: :_blank %>
        </p>
      </div>

      <a class="btn btn-lg btn-default your-card-button hide-for-desktop">unlock my swag</a>
      <div class="your-card-mobile hide-for-desktop">
        <a href="#your-card" data-toggle="modal" data-target="#myModal">Your Secret Card</a>
      </div>
    </div>

  </div>

</div>

app/views/pages/_your_card.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade card-modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Queen of My Heart</h4>

        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p><img class="card-img" src="https://i.imgur.com/TG6UKVC.png"></p>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div> -->
    </div>

  </div>
</div>

app/views/pages/index.html.erb
<div class="pages">
  <%= render "home" %>
  <%= render "about" %>
  <%= render "career_journey" %>
  <%= render "contact" %>
</div>